# Generated by Django 4.0.3 on 2022-04-14 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendita', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.CharField(default='prueba', max_length=100),
            preserve_default=False,
        ),
    ]
